site_name: How to chaberch

theme:
  name: material

nav:
  - Welcome: index.md
  - Getting started: getting-started.md
  - Base: base.md
  - Markdown: markdown.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
